name: Ruff
on: [ pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install ruff

      - name: Get changed Python files
        id: changed-py-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.py

      - name: Run Ruff
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: ruff check --output-format=github ${{ steps.changed-py-files.outputs.all_changed_files }} --force-exclude
