name: Semgrep
on: [ pull_request ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pipx install semgrep

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files_ignore: |
            **/tests/**
            **/conftest.py

      - name: Run Semgrep on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          semgrep scan \
                  --config auto \
                  --json \
                  ${{ steps.changed-files.outputs.all_changed_files }} \
                  > results.json

      - uses: drew2a/annotate-semgrep-action@v1
        with:
          json_path: "results.json"
          fail_on: "ERROR,WARNING"
